### ISSUE TITLE
cant get working

### ISSUE THREAD

**Issue by reitenth** [noggl/AniPlanrr#3]
![image](https://github.com/noggl/AniPlanrr/assets/94771708/1835a35b-0d04-4a8d-a322-8f4dba20b57e)

![image](https://github.com/noggl/AniPlanrr/assets/94771708/68ff2cab-347a-4331-95be-cf3af5ddfdb7)

**Comment by reitenth** [comment]
i changed the localhost to ip as im using a custom network. now im getting this.

![image](https://github.com/noggl/AniPlanrr/assets/94771708/474cc267-b860-466f-9c35-d7cfd217f5be)

**Comment by noggl** [comment]
Are you running AniPlanrr in Docker or locally?
Is the device running AniPlanrr the same device that is running Sonarr?

**Comment by reitenth** [comment]
both are on same machine and aniplanrr is in docker on unraid

**Comment by noggl** [comment]
You said that you're now using the IP address of the sonarr server and are getting an error that the response isn't 200, right? 

Let me update the code real quick to see what's happening.

**Comment by reitenth** [comment]
yes i am using the ip address, it looks like this. http://192.168.1.136:8989/api/

**Comment by noggl** [comment]
Ok, try it again, it should tell you what the error code is now. If it's 401, it's not accepting your authentication, so maybe the API Key is wrong. You can check the API key for Sonarr in the Web UI in Settings->General->API Key

You can also set LOGGING=TRUE in your environment for AniPlanrr and it'll spit out a bunch of logs into the configs folder. The one you'll want is "failedSonarrResponse".

You'll probably need to pull the new image, or clear your docker image cache after removing the current image.

**Comment by reitenth** [comment]
![image](https://github.com/noggl/AniPlanrr/assets/94771708/020d1940-e365-43c2-980c-fa8f32d849a4)

this is the new log

**Comment by reitenth** [comment]
this is the log with logging=true env variable. not much there.

![image](https://github.com/noggl/AniPlanrr/assets/94771708/25a9107c-18cb-4bef-ad66-d3e12046932f)

**Comment by noggl** [comment]
sorry that was a whoopsie on my part. You should get the response code if you pull again in about 5 minutes.

If you're doing `LOGGING=True`, you'll get a bunch of files in the log folder. You want failedSonarrResponse-dump.txt

**Comment by noggl** [comment]
seems that github actions aren't working so it won't create the new image. I'll let you know when it's resolved.

**Comment by reitenth** [comment]
only thing new as of now is it saying sonarr is 404, not 200

**Comment by noggl** [comment]
404 means Sonarr isn't found at the URL that you put in.
What happens if you go to `http://192.168.1.136:8989/api/` in your browser?

**Comment by reitenth** [comment]
just a complete black screen. if i remove /api i get to sonarr.

one of the devs on the sonarr sub said this to me. 
"why is this calling to /api/series and not /api/v3/series?" (or v4 im assuming if using that).

**Comment by noggl** [comment]
v3 works too, I could change it but isn't a problem in my tests.

What _is_ a problem is that your API is unreachable. Regardless of what I'm doing, you should get a response when you go to `http://192.168.1.136:8989/api/`, `http://192.168.1.136:8989/api/series`, and `http://192.168.1.136:8989/api/v3/series` Are you using some kind of reverse proxy? I think I might need to understand how you're running Sonarr.

If you get a different response when going to `http://192.168.1.136:8989/api/series` vs `http://192.168.1.136:8989/api/v3/series`, I can make a branch where I change it for you, but they work the same for me.

**Comment by reitenth** [comment]
i do have a reverse proxy but it also does not work when i put /api at the end. the 192.168.1.136:8989/api is all local. my reverse proxy is sonarr.xxxxxxxxxxxxxx.or. im using this for proxy https://github.com/linuxserver/docker-swag

**Comment by noggl** [comment]
did api/v3/series do anything differently? If you can't access the api from the URL that the API is supposed to be at, it's something with your sonarr or proxy config.

**Comment by reitenth** [comment]
this works http://192.168.1.136:8989/api?apikey=myapikeyhere

**Comment by noggl** [comment]
Go to `http://192.168.1.136:8989/api/series?apikey=yourapikey` and post the results. If that doesn't give a long output (all your sonarr shows), do `http://192.168.1.136:8989/api/v3/series?apikey=yourapikey` and post that.

and in case it wasn't clear, replace yourapikey with your api key

**Comment by reitenth** [comment]
the first one is a black screen still. the second one has like 700 lines of this
![image](https://github.com/noggl/AniPlanrr/assets/94771708/a2efb3c9-3392-4531-8fb7-4cc416762c2a)

**Comment by noggl** [comment]
Okay, for some reason v3 is necessary in your config but not in mine. I'll make a branch that uses v3 for you to test, let me know if that fixes it.

While I'm doing that, could you click on the ...s and confirm that they have your show data inside? With 400+ entries I'm assuming it does

**Comment by noggl** [comment]
Wait, I've got a better idea, just add v3 to the end of the API URL in your environment variable

so it would be `http://192.168.1.136:8989/api/v3/`

**Comment by reitenth** [comment]
i am using sonarr v4 if that could be why its not working? adding v3 seemed to do the trick! unfortunately it does seem to be doing anything? nothing got added. 
![image](https://github.com/noggl/AniPlanrr/assets/94771708/7ddbafb0-f96d-470d-b819-77d65db9d979)

**Comment by reitenth** [comment]
also adding v3 didnt seem to work for radarr

**Comment by reitenth** [comment]
here is the addshowreponse-dump log https://gist.github.com/reitenth/a8279a8bc0d1c8024dcb87daccef70d2
here is the addshowshow-dump log       https://gist.github.com/reitenth/05fed98ef6165406eb6860ba244d9217

**Comment by noggl** [comment]
v3 won't work for radarr since that already had v3 in parts of the code. I'll try to convert fully over to v3 after we get sonarr working.

I just pushed an update to give a bit more data, could you tell me what happens now, and send me your searchResponse-dump?

**Comment by stevietv** [comment]
@noggl - perhaps good for you to know that Sonarr v4 has had the old API endpoint sun-setted, and all API traffic should be directed to api/v3/ endpoints. (note that v4 sonarr will continue to use v3 API - versioning of UI and API is independent of each other).
You could do this smoothly by migrating everything to the /v3/ endpoint. or performing a check on the basis /api endpoint for the current API version of the sonarr server is accessing.

**Comment by reitenth** [comment]
here is the search response dump https://gist.github.com/reitenth/467561344916306eb96663300927985c

**Comment by thezoggy** [comment]
and to note, sonarr api docs - https://sonarr.tv/docs/api/
sonarr 3+4  use sonarr v3 api.  sonarr api version does not align with the program major version.

**Comment by noggl** [comment]
thanks for all the comments! I switched over to the v3 api for Sonarr, and I was already using the v3 api for Radarr so there's no /v3 needed for either. @reitenth try just `http://192.168.1.136:8989/api/` now and see if that works.

Regarding it "not doing anything", I think it's just not finding the matches. Try adding "A Galaxy Next Door" to your list as a test, since the title for that show in AniList and TVDB are the same. Since there's no ID that Sonarr/Radarr and AniList share, I don't have a way to compare them outside of the manual mapping.csv. I think XEM might help but I haven't figured that out yet. Until then I've been thinking of creating a repository for a community mapping.csv file. Would that be a reasonable solution for the mapping issue?

**Comment by thezoggy** [comment]
xem is not an anidb<>tvdb mapping service..   

however, every series in xem *should* have a tvdbid (kinda needed to make sick*/sonarr/medusa/etc work), and several of those that are anime DO have an anidb (or multiple) ids.

Now as the info in xem is pretty static, especially when you really just need series id. Rather than having ever user hit xem (dunno the user base size of your app) but it you might be best off just pulling down info and massage it to the format you want for your mapping csv and store that on github. Then have your app pull that csv down on startup so it gets latest data on each boot.. and to update just restart. 

Now for xem api, sadly I do not have any nice fancy openapi/swagger doc as was created before that even existed :x 

So I'll just hit the highlights here for ya.

To see what series that have mapping info, you could use:
https://thexem.info/map/havemap?origin=tvdb
https://thexem.info/map/havemap?origin=anidb

To see what aliases for the entity (defaultNames = the name in xem for the show itself, which is **usually** the tvdb name):
http://thexem.info/map/allNames?origin=tvdb&defaultNames=True

If you wanted to see the aliases, include the season number for the aliases (if its a season alias), and do it from anidb pov for the ids you would do:
http://thexem.info/map/allNames?origin=anidb&seasonNumbers=True&defaultNames=True

**Comment by noggl** [comment]
@reitenth, were you able to get it working after that fix?

**Comment by reitenth** [comment]
nope, im assuming its because the ids dont match for pretty much anything, but that is just a guess. thanks.

**Comment by reitenth** [comment]
im testing with my happy marriage at the moment. 
https://thetvdb.com/series/watashi-no-shiawase-na-kekkon

**Comment by noggl** [comment]
Could you try adding [A Galaxy Next Door,](https://anilist.co/anime/148098/Otonari-ni-Ginga) to see if that works?

**Comment by reitenth** [comment]
it did not. the logs have a bunch of stuff. 
![image](https://github.com/noggl/AniPlanrr/assets/94771708/04f494d3-7437-44f6-b978-08a52f851cd3)

**Comment by noggl** [comment]
Sorry, there were a bunch of changes on the latest version, so make sure you pull that. Make sure that your docker compose matches the current format (specifically your sonarr url shouldn't include the /api at the end)

**Comment by reitenth** [comment]
still cant get it going. here are the logs and my compose, maybe its wrong somewhere.
![image](https://github.com/noggl/AniPlanrr/assets/94771708/3d960e71-2b70-4ba5-a5ab-534c0356fb00)

**Comment by reitenth** [comment]
![image](https://github.com/noggl/AniPlanrr/assets/94771708/4e3be4e9-07d1-4d11-9c21-72421c9997de)

**Comment by noggl** [comment]
I think you're using an old container. Did you manually pull the latest container? Docker won't automatically pull latest containers if you already have one cached.

If you were on the latest container I would expect to see "Running setupSonarr function!" before "Getting Sonarr List".

Also, if you give it the url and key for Radarr, you need to specify the path for that too.

Last, are you sure that's the right path for Sonarr? It should be the URL as Sonarr sees it, not your host system. If you log in to Sonarr, it should be a path listed under Settings -> Media Management -> Root Folders.

**Comment by noggl** [comment]
To check if you're on the latest container, run `docker inspect aniplanrr2 | grep image.revision`. It should match the latest commit hash, `3e29908df600f99d11421b190ce88554e9db30ff`.

**Comment by reitenth** [comment]
my bad, pulled the latest container. also changed the path to the sonarr root folder. not seeing a galaxy next door in sonarr still. the logs look like its running though
![image](https://github.com/noggl/AniPlanrr/assets/94771708/d3ccb10e-4800-4003-b4ff-b07a5962b411)

**Comment by reitenth** [comment]
did get some entries added to radarr correctly, however.

**Comment by noggl** [comment]
The log you posted seems to show the container mid-sync. Please wait until it says "Sleeping for 3600 seconds" and post the log file from the beginning of the sync up to that point, if you still don't see a galaxy next door.

Glad some of them are syncing, probably the ones that match perfectly in name. I'm still looking for a good solution for shows that don't match in title, so hopefully it'll improve soon!

**Comment by reitenth** [comment]
which log file? there are a lot. searchresponse dump?

**Comment by noggl** [comment]
just the regular log.txt. That should be the same as what you are screenshotting. If it's easier you can paste the docker log instead.

**Comment by reitenth** [comment]
![image](https://github.com/noggl/AniPlanrr/assets/94771708/86d188e5-1c8f-468a-869c-4c3eb303b361)

**Comment by noggl** [comment]
Just pushed a change that should fix that particular mapping issue (some titles on TVDB have (YEAR) in the name, which fails since AniList doesn't do that).

I also made another project with a mapping.csv file built from some resources online, give it a shot and see if that helps with some of your mapping problems. I'd like to include this in the repo itself eventually, but there have been a lot of changes so some general cleanup is needed.

**Comment by reitenth** [comment]
![image](https://github.com/noggl/AniPlanrr/assets/94771708/160065b9-8cf5-46fd-9acc-327e3afdf55b)

still cant get it for some reason. it says on the readme not to use that mappings file as to not overload xem , is it ok to use?

**Comment by thezoggy** [comment]
> 

looking at your script, you are not using the xem api. you instead are web scraping.. getting a list of shows then going to each page to get data. this is hugely wasteful and a good way to get your ip banned from abuse. 

please use the api commands like i suggest before to get the data you want. you should not need to do 3,000+ hits to the server.

**Comment by thezoggy** [comment]
> ![image](https://user-images.githubusercontent.com/94771708/245628553-160065b9-8cf5-46fd-9acc-327e3afdf55b.png)
> 
> still cant get it for some reason. it says on the readme not to use that mappings file as to not overload xem , is it ok to use?

"ERRROR" has one to many R's. 
Also hard to read the log messages to know where the show name start/stops from the action to the item.

**Comment by noggl** [comment]
> it says on the readme not to use that mappings file as to not overload xem , is it ok to use?

The instructions say not to run the script, so don't run the script. Just download the [completely static mapping.csv file](https://raw.githubusercontent.com/noggl/AniListToTVDB/main/mapping.csv) and point AniPlanrr to that as your mapping.csv as per the readme on AniPlanrr.

Again, DO NOT run the AniListToTVDB python scripts, since you don't need to. The scripts create the [mapping.csv](https://raw.githubusercontent.com/noggl/AniListToTVDB/main/mapping.csv) file that you can just download from the repo

Regarding your error, I've got it on my end too, it's a problem with the season setting function that I'm working on. I've only seen that happen when A Galaxy Next Door is already in Sonarr, can you confirm that is not the case?

**Comment by noggl** [comment]
@thezoggy Which API Commands are those? Looking at the documentation and in my searching, I can't find any API Request that returns the IDs used by multiple providers.

**Comment by noggl** [comment]
@thezoggy None of the requests detailed at https://thexem.info/doc provide IDs from TVDB or AniDB, and the closest calls (https://thexem.info/map/havemap?origin=tvdb and https://thexem.info/map/havemap?origin=anidb) don't have any data to relate to one another. If there is a way to get both the TVDB ID and the AniDB ID from XEM, that's all thats needed. Even if there's just a way to get the ID from TVDB and AniDB and the ID used on the xem website (for example, [4693 for 7SEEDS](https://thexem.info/xem/show/4693), I can do the matching on my end.

>this is hugely wasteful

You are right, I agree that I need to change this. If you would like I can remove the scrape.py file from the repo to prevent anyone else from using it. If there is an API Request or Requests that provides the data above, I would love to use that instead of the inefficient, stupid, scraping.

**Comment by thezoggy** [comment]
> @thezoggy None of the requests detailed at https://thexem.info/doc provide IDs from TVDB or AniDB, and the closest calls (https://thexem.info/map/havemap?origin=tvdb and https://thexem.info/map/havemap?origin=anidb) don't have any data to relate to one another. If there is a way to get both the TVDB ID and the AniDB ID from XEM, that's all thats needed. Even if there's just a way to get the ID from TVDB and AniDB and the ID used on the xem website (for example, [4693 for 7SEEDS](https://thexem.info/xem/show/4693), I can do the matching on my end.
> 
> > this is hugely wasteful
> 
> You are right, I agree that I need to change this. If you would like I can remove the scrape.py file from the repo to prevent anyone else from using it. If there is an API Request or Requests that provides the data above, I would love to use that instead of the inefficient, stupid, scraping.

I noted it all in https://github.com/noggl/AniPlanrr/issues/3#issuecomment-1581785625

**Comment by thezoggy** [comment]
> @thezoggy Which API Commands are those? Looking at the documentation and in my searching, I can't find any API Request that returns the IDs used by multiple providers.

There is no anidb<>tvdb command, you would get anidb list and then get tvdb list then build your map. 

Depending on what you need, you could do something like:
http://thexem.info/map/allNames?origin=tvdb&seasonNumbers=True&defaultNames=True
http://thexem.info/map/allNames?origin=anidb&seasonNumbers=True&defaultNames=True

Then match up based on alias name (default/series wide/season). 

If you did not realize, the id for xem has nothing to do with an entity. They will change anytime a draft gets promoted/demoted, as that new draft id replaces the previous.. somewhat like a git commit for a file.

**Comment by thezoggy** [comment]
I havent really touched xem code in 10+ years, so I can't make any promises that I'll add another api endpoint just for your purpose. But I should have some free cycles soonish to poke around.

**Comment by noggl** [comment]
@thezoggy. I did see those, but the issue with that endpoint is that it only gives one ID per show, when the XEM website has multiple AniDB entries for the different seasons. 
For example, the http://thexem.info/map/allNames?origin=anidb&seasonNumbers=True&defaultNames=True endpoint contains:
`"11370":["Re:Zero -Starting Life in Another World-",{"ReZero kara Hajimeru Isekai Seikatsu":-1},{"Re Zero kara Hajimeru Isekai Seikatsu":-1},{"Re: Zero Kara Hajimeru Isekai Seikatsu":-1},{"ReZero kara Hajimeru Isekai Seikatsu (Season 2)":2},{"Re:ZERO -Starting Life in Another World- Season 2":2}]` 
but [the xem website has the ids for all 3 seasons in AniDB](https://thexem.info/xem/show/5338), not just the first one which is what the API returns. 

I'm happy to re-write the script that I made since I don't like it scraping the website (again just let me know if you want me to remove that file from the repo).

>If you did not realize, the id for xem has nothing to do with an entity. They will change anytime a draft gets promoted/demoted, as that new draft id replaces the previous.. somewhat like a git commit for a file.

Good to know!

>I havent really touched xem code in 10+ years, so I can't make any promises that I'll add another api endpoint just for your purpose. But I should have some free cycles soonish to poke around.

My PHP is pretty rusty and without example data to use to test it'll be slow going, but if I can figure anything out I'll let you know!

**Comment by noggl** [comment]
@thezoggy I've re-written the [AniListToTVDB](https://www.github.com/noggl/AniListToTVDB) repo to use [anime-lists](https://github.com/Fribb/anime-lists) instead of XEM. I still think it would be cool to be able to query XEM for AniDB IDs, but it's not necessary anymore (it would be more for a "double check" against the current data sources.

@reitenth the [csv is available here](https://raw.githubusercontent.com/noggl/AniListToTVDB/main/mapping.csv) if you want to use it. It's much more complete than the old one. Let me know if you have any questions or if you find things that aren't working
